name: SlideKitPresentation
packages:
  SlideKit:
    url: https://github.com/mtj0928/SlideKit
    from: 0.1.0
targets:
  SlideKitPresentation:
    type: application
    settings:
      base:
        INFOPLIST_FILE: SlideKitPresentation/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.github.mtj0928.SlideKit.demo.SlideKitPresentation
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    platform: iOS
    deploymentTarget: "15.0"
    sources: [SlideKitPresentation]
    dependencies:
      - package: SlideKit
