//
//  TitleSlide.swift
//
//  This file is automatically generated by SlideGen
//

import SlideKit
import SwiftUI

struct TitleSlide: Slide {

    var body: some View {
        VStack {
            Text("Self Introduction")
                .font(.system(size: 260))
            .padding(12)
        }
    }
}

struct TitleSlide_Previews: PreviewProvider {
    static var previews: some View {
        SlidePreview {
            TitleSlide()
        }
    }
}
